name: quiz_game
description: "問答遊戲"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: latest_version
  firebase_auth: latest_version
  cloud_firestore: latest_version
  google_mobile_ads: latest_version
  in_app_purchase: latest_version

flutter:
  uses-material-design: true
